sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t petarda/docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true petarda/docker-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-909829755193"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
